[package]
name = "alef-parser"
version = "0.1.0"
edition = "2018"
authors = ["Edoardo Marangoni <ecmma@anche.no>"]

[dependencies]
anyhow = "1.0.52"
log = "0.4.14"
owo-colors = "3.1.0"
paste = "1.0.6"
phf = { version = "0.10", features = ["macros"] }
textwrap = "0.14.2"
thiserror = "1.0.30"
